// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Migrate/introspect need a direct (non-pooled) connection — Supabase's
  // pooled port doesn't support the prepared statements they issue.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
